### PR TITLE
Feature: Add timer countdown to waits

### PR DESCRIPTION
**Pull request by JustinHallquist**
First off, thank you so much for making this tool -- it's phenomenal and I have been using it for ages now!

feat: Add Timer Countdown

This PR adds a configurable timer to the Waits training mode.
The goal is to mimic both real life scenarios which are time pressured, especially online matches, as well as tests material with time restraints like maru-jan. 

**Notes:**

- Please feel free to reject / edit this as you see fit -- though this is a feature that has been on my wish list, I completely understand if the interest otherwise isn't there.
- I am unsure if the translations to eo/es are correct in context (auto translated and cross referenced to my best ability).
- If manual testing isn't enough, I can add automated tests if needed.

**Changes:**

- Adds a timer preference with the options of [Off, 10, 30, 60] (seconds) -- these values are not based on any rigorous requirements so if others are preferred (such as 24 to mimic online), it's an easy update.
- Adds a countdown below it that displays remaining duration.
- When the timer is enabled:
  - each new hand resets the timer
  - an expiring timer triggers a ConfirmSelected message
  - changing the timer duration triggers a GenerateTiles message
- Adds translations for new labels

**Testing:**

- Manually tested the timer functionality with different timer durations, ensuring it starts, updates, and stops correctly.
- Verified that the timer resets when generating a new hand.
- Confirmed that the timer does not start when the timer duration is set to Off.
- Checked both light / dark mode visibility.

**Screenshots:**
Default Off:

image

Timer running and hand submitted:
brave_ynp5iyhyep

Timer expires:

brave_t8P0IhA3HI

### CODE REVIEW

**Comment by djuretic** [comment]
That's great @JustinHallquist! Give me some time to review it, I've been very busy lately.

**Comment by JustinHallquist** [comment]
No rush and thank you for taking the time!

**Comment by djuretic** [comment]
@JustinHallquist wonderful job! :medal_sports:   I'll merge this and fix some translations, thanks for the pull request.

I'd like to hear your feedback, what are the things you like the most about this tool?

Edit: Your changes are now live!

**Comment by JustinHallquist** [comment]
Hey @djuretic, thanks for the review! (and sorry for making work for you on the translations)
On review as to why I enjoy this wait trainer, I believe it hits pretty hard on some of the golden rules for good feature dev:
* Does one thing well
* Design is clean, responsive, simplistic, and obvious
* Fast
The skill settings (block count + min wait count) and animation really helped me when I was new. I started at 4 tiles and incremented the # of waits until I was comfortable adding another block, rinse repeat.
Now I use it as a timed 13 tile chiniisou trainer -- just leave the tab on the side and hammer a few out during breaks in the day.
I've used some other tools before finding this one and they were much clunkier or more of an afterthought as part of a larger suite of mahjong training tools.
So overall, it's just great at what it does.
Again, thank you so much for this!

**Comment by djuretic** [comment]
Thanks a lot for your feedback @JustinHallquist ! I'm so glad it has been useful to you.

**Pull request merged**
